name: frontend-triv-test
services:
  frontend-triv-react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-triv-react
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge
